# Generated by Django 5.1.1 on 2024-10-31 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cargo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cuadrilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cuadrilla', models.CharField(blank=True, max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoCuadrilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuadrilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppTareas.cuadrilla')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppTareas.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tarea', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_inicio_planificada', models.DateField()),
                ('fecha_termino_planificada', models.DateField()),
                ('observacion_jefe', models.TextField(blank=True, null=True)),
                ('cuadrilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppTareas.cuadrilla')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppTareas.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Subtarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_subtarea', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_inicio_planificada', models.DateField()),
                ('fecha_termino_planificada', models.DateField()),
                ('fecha_inicio_real', models.DateField(blank=True, null=True)),
                ('fecha_termino_real', models.DateField(blank=True, null=True)),
                ('observacion_capataz', models.TextField(blank=True, null=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppTareas.tarea')),
            ],
        ),
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppTareas.tarea')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=20)),
                ('primer_apellido', models.CharField(max_length=20)),
                ('segundo_apellido', models.CharField(max_length=20)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppTareas.cargo')),
                ('cuadrilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppTareas.cuadrilla')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppTareas.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=20)),
                ('primer_apellido', models.CharField(max_length=20)),
                ('segundo_apellido', models.CharField(max_length=20)),
                ('correo_electronico', models.EmailField(max_length=100)),
                ('contrasena', models.CharField(max_length=255)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppTareas.cargo')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppTareas.estado')),
            ],
        ),
        migrations.AddField(
            model_name='cuadrilla',
            name='capataz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppTareas.usuario'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['rut'], name='AppTareas_u_rut_bd2078_idx'),
        ),
    ]
