# Generated by Django 5.1.1 on 2024-11-02 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTareas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progreso',
            name='tarea',
        ),
        migrations.RemoveIndex(
            model_name='usuario',
            name='AppTareas_u_rut_bd2078_idx',
        ),
        migrations.AddField(
            model_name='trabajador',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cuadrilla',
            name='capataz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuadrillas_dirigidas', to='AppTareas.trabajador'),
        ),
        migrations.DeleteModel(
            name='Progreso',
        ),
    ]
