# Generated by Django 5.1.1 on 2024-11-02 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTareas', '0002_remove_progreso_tarea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadrilla',
            name='capataz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuadrillas_dirigidas', to='AppTareas.usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cuadrilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppTareas.cuadrilla'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Trabajador',
        ),
    ]
