# Generated by Django 5.1.1 on 2024-11-09 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTareas', '0003_alter_cuadrilla_capataz_usuario_cuadrilla_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='subtarea',
            name='observacion_capataz',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='cuadrilla',
        ),
        migrations.AddField(
            model_name='subtarea',
            name='cuadrilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppTareas.cuadrilla'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_comentario', models.TextField()),
                ('fecha_comentario', models.DateTimeField(auto_now_add=True)),
                ('respuesta_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppTareas.comentario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppTareas.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='tarea',
            name='comentarios',
            field=models.ManyToManyField(blank=True, related_name='tareas', to='AppTareas.comentario'),
        ),
        migrations.AddField(
            model_name='subtarea',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppTareas.estadotarea'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppTareas.estadotarea'),
        ),
    ]
