# Generated by Django 5.1.1 on 2024-11-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTareas', '0004_estadotarea_remove_subtarea_observacion_capataz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtarea',
            name='comentarios',
            field=models.ManyToManyField(blank=True, related_name='subtareas', to='AppTareas.comentario'),
        ),
    ]
